name: _build
on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
    outputs:
      sha:
        description: Git SHA
        value: ${{ jobs.build.outputs.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      sha: ${{ steps.meta.outputs.sha }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - id: meta
        run: echo "sha=${GITHUB_SHA}" >> "$GITHUB_OUTPUT"
      - name: Warm cache (no push)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          load: false
          tags: ${{ inputs.image_name }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max