name: Build and Deploy
on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

env:
  IMAGE_NAME: ghcr.io/miroslavnecas/website
  DOCKER_BUILDKIT: "1"

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    outputs:
      digest: ${{ steps.push.outputs.digest }}
    steps:
      - uses: actions/checkout@v4

      # Use the local Docker daemon's BuildKit (no external BuildKit image pull)
      - uses: docker/setup-buildx-action@v3
        with:
          driver: docker

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
          provenance: false

  deploy:
    needs: build_and_push
    runs-on: ubuntu-latest
    steps:
      - name: SSH deploy (root)
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: root
          key: ${{ secrets.SSH_KEY }}
          script_stop: true
          script: |
            set -e
            cd /home/website

            IMAGE_LINE="IMAGE=${{ env.IMAGE_NAME }}@${{ needs.build_and_push.outputs.digest }}"
            touch .env
            if grep -qE '^IMAGE=' .env; then
              sed -i -E "s|^IMAGE=.*|$IMAGE_LINE|" .env
            else
              echo "$IMAGE_LINE" >> .env
            fi

            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
            docker compose pull personal_website || true
            docker compose up -d personal_website --force-recreate
            docker image prune -f
